title: "Natron"
description: Open Source Compositing Software For VFX and Motion Graphics
url: ""
baseurl: ""

# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: "false"
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
plugins:
  - jekyll-feed
  - jekyll-redirect-from